"""user_category_rules and user_corrected

Revision ID: 139facb0dd05
Revises: cf17d3bef34d
Create Date: 2026-03-22 19:14:02.938480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139facb0dd05'
down_revision: Union[str, Sequence[str], None] = 'cf17d3bef34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_corrected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'user_corrected')
    # ### end Alembic commands ###
